# Create a view
CREATE VIEW EMPSALARY AS
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, SALARY
FROM EMPLOYEES;
SELECT * FROM EMPSALARY;

# Update a view
CREATE OR REPLACE VIEW EMPSALARY AS
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, JOB_TITLE,
MIN_SALARY, MAX_SALARY
FROM EMPLOYEES as E, JOBS as J
WHERE E.JOB_ID = J.JOB_IDENT;
SELECT * FROM EMPSALARY;

# Drop a View
DROP VIEW EMPSALARY;

# Create a view “EMP_DEPT” which has the following information:
# EMP_ID, FNAME, LNAME and DEP_ID from EMPLOYEES table
CREATE VIEW EMP_DEPT AS
SELECT EMP_ID, F_NAME, L_NAME, DEP_ID
FROM EMPLOYEES;

/*Modify “EMP_DEPT” such that it displays Department names instead of Department IDs.
 For this, we need to combine information from EMPLOYEES and DEPARTMENTS as follows.
*/
CREATE OR REPLACE VIEW EMP_DEPT AS
SELECT EMP_ID, F_NAME, L_NAME, DEP_NAME
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEP_ID = DEPARTMENTS.DEPT_ID_DEP;